---
- name: Pull facts on hypervisor
  action: setup
  delegate_to: "{{ hypervisor }}"

- name: Install additional packages - RedHat Host
  yum: name={{ item }} state=present
  with_items:
   - qemu-kvm
   - libvirt
   - bridge-utils
   - libvirt-python
  when: ansible_os_family == "RedHat"
  delegate_to: "{{ hypervisor }}"

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create installtion directory
  file: path={{ images_path }}{{ vnf_version}} state=directory owner={{ libvirt.user }} group={{ libvirt.group }}
  delegate_to: "{{ hypervisor }}"

- name: Copy over qcow2 image
  copy: src=files/{{ vnf_qcow2 }} dest={{ images_path }}{{ vnf_version}}/{{ inventory_hostname }}.qcow2 owner={{ libvirt.user }} group={{ libvirt.group }} force=no
  delegate_to: "{{ hypervisor }}"
